import { setupAccordion } from "./accordion-nested/front-scripts";
import { setupBackToTop } from "./back-to-top/front-scripts";
import { setupContentSlider } from "./content-slider/front-scripts";
import { setupDateCountdown } from "./date-countdown/front-scripts";
import { setupForm } from "./form-wrap/front-scripts";
import { setupIcon } from "./icon/front-scripts";
import { setupMasonry } from "./masonry-wrap/front-scripts";
import { setupMenu } from "./menu-wrap/front-scripts";
import { setupNumberCounter } from "./number-counter/front-scripts";
import { setupPopup } from "./popup/front-scripts";
import { setupPostGrid } from "./post-grid/front-scripts";
// import { setupPostGridFilterable } from "./post-grid-filterable/front-scripts";
import { setupPostGridFilterableNav } from "./post-grid-filterable-nav/front-scripts";
import { setupProgressBar } from "./progress-bar/front-scripts";
import { setupTabs } from "./tabs-nested/front-scripts";
import { setupText } from "./text/front-scripts";
import { setupWooAddToCart } from "./woo-add-to-cart/front-scripts";
import { setupWooMyAccount } from "./woo-my-account/front-scripts";
import { setupWooProductTabs } from "./woo-product-tabs/front-scripts";
setupAccordion();
setupBackToTop();
setupContentSlider();
setupDateCountdown();
setupForm();
setupIcon();
setupMasonry();
setupMenu();
setupNumberCounter();
setupPopup();
setupPostGrid();
setupProgressBar();
setupTabs();
setupText();
setupWooAddToCart();
setupWooMyAccount();
setupWooProductTabs();
setupPostGridFilterableNav();

// setupPostGridFilterable();

